function Rae2021BoronDataS1 = importd11BData(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  RAE2021BORONDATAS1 = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  RAE2021BORONDATAS1 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  RAE2021BORONDATAS1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Rae2021BoronDataS1 = importfile("C:\Users\Ross\Documents\Work\Postdoc\St_Andrews\Output\Analysis\PETM_deltaCO2\Data\Rae_2021_Boron_Data.xlsx", "d11Bdata_byStudy", [2, 819]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Feb-2022 17:02:45

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 819];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 16);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":P" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["ref", "site", "age", "salinity", "temperature", "depth", "species", "d11B", "d11B_2SD", "calibration", "symbol", "colour", "size", "exclude", "notes", "time"];
opts.VariableTypes = ["categorical", "categorical", "double", "double", "double", "double", "categorical", "double", "double", "categorical", "categorical", "categorical", "double", "double", "categorical", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["ref", "site", "species", "calibration", "symbol", "colour", "notes", "time"], "EmptyFieldRule", "auto");

% Import the data
Rae2021BoronDataS1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":P" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Rae2021BoronDataS1 = [Rae2021BoronDataS1; tb]; %#ok<AGROW>
end

end