function Rae2021BoronDataS3 = importd11BswData(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  RAE2021BORONDATAS3 = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  RAE2021BORONDATAS3 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  RAE2021BORONDATAS3 = IMPORTFILE(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Rae2021BoronDataS3 = importfile("C:\Users\Ross\Documents\Work\Postdoc\St_Andrews\Output\Analysis\PETM_deltaCO2\Data\Rae_2021_Boron_Data.xlsx", "d11Bsw", [2, 18]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Feb-2022 21:15:13

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 18];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":F" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["age", "d11Bsw", "uncertainty", "d11Bsw_low", "d11Bsw_high", "source"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "categorical"];

% Specify variable properties
opts = setvaropts(opts, "source", "EmptyFieldRule", "auto");

% Import the data
Rae2021BoronDataS3 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":F" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Rae2021BoronDataS3 = [Rae2021BoronDataS3; tb]; %#ok<AGROW>
end

end